export enum EventType {
  WORKOUT_CREATED = "WORKOUT_CREATED",
  WORKOUT_UPDATED = "WORKOUT_UPDATED",
  WORKOUT_DELETED = "WORKOUT_DELETED",
  TOTAL_WORKOUT_UPDATED = "TOTAL_WORKOUT_UPDATED",
  BADGE_AWARDED = "BADGE_AWARDED",
}
