export enum OutboxStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  PUBLISHED = "PUBLISHED",
  FAILED = "FAILED",
}

export const EventTypes = {
  WORKOUT_CREATED: "WORKOUT_CREATED",

  TOTAL_WORKOUT_UPDATED: "TOTAL_WORKOUT_UPDATED",

  BADGE_AWARDED: "BADGE_AWARDED",

  NOTIFICATION_CREATED: "NOTIFICATION_CREATED",
} as const;
